/*
 * This file is part of the WebKit open source project.
 * This file has been generated by generate-bindings.pl. DO NOT MODIFY!
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "config.h"
#include "RBInitialization.h"

#include "RBAbstractWorker.h"
#include "RBAnalyserNode.h"
#include "RBArrayBuffer.h"
#include "RBArrayBufferView.h"
#include "RBAttr.h"
#include "RBAudioBuffer.h"
#include "RBAudioBufferSourceNode.h"
#include "RBAudioContext.h"
#include "RBAudioDestinationNode.h"
#include "RBAudioListener.h"
#include "RBAudioNode.h"
#include "RBAudioParam.h"
#include "RBAudioProcessingEvent.h"
#include "RBAudioSourceNode.h"
#include "RBBarInfo.h"
#include "RBBeforeLoadEvent.h"
#include "RBBiquadFilterNode.h"
#include "RBBlob.h"
#include "RBCanvasGradient.h"
#include "RBCanvasPattern.h"
#include "RBCanvasProxy.h"
#include "RBCanvasRenderingContext.h"
#include "RBCanvasRenderingContext2D.h"
#include "RBCDATASection.h"
#include "RBChannelMergerNode.h"
#include "RBChannelSplitterNode.h"
#include "RBCharacterData.h"
#include "RBClientRect.h"
#include "RBClientRectList.h"
#include "RBClipboard.h"
#include "RBCloseEvent.h"
#include "RBComment.h"
#include "RBCompositionEvent.h"
#include "RBConsole.h"
#include "RBConvolverNode.h"
#include "RBCoordinates.h"
#include "RBCounter.h"
#include "RBCrypto.h"
#include "RBCSSCharsetRule.h"
#include "RBCSSFontFaceLoadEvent.h"
#include "RBCSSFontFaceRule.h"
#include "RBCSSHostRule.h"
#include "RBCSSImportRule.h"
#include "RBCSSMediaRule.h"
#include "RBCSSPageRule.h"
#include "RBCSSPrimitiveValue.h"
#include "RBCSSRule.h"
#include "RBCSSRuleList.h"
#include "RBCSSStyleDeclaration.h"
#include "RBCSSStyleRule.h"
#include "RBCSSStyleSheet.h"
#include "RBCSSSupportsRule.h"
#include "RBCSSUnknownRule.h"
#include "RBCSSValue.h"
#include "RBCSSValueList.h"
#include "RBCustomElementConstructor.h"
#include "RBCustomEvent.h"
#include "RBDatabase.h"
#include "RBDatabaseSync.h"
#include "RBDataTransferItem.h"
#include "RBDataTransferItemList.h"
#include "RBDataView.h"
#include "RBDedicatedWorkerContext.h"
#include "RBDelayNode.h"
#include "RBDeviceMotionEvent.h"
#include "RBDeviceOrientationEvent.h"
#include "RBDirectoryEntry.h"
#include "RBDirectoryEntrySync.h"
#include "RBDirectoryReader.h"
#include "RBDirectoryReaderSync.h"
#include "RBDocument.h"
#include "RBDocumentFragment.h"
#include "RBDocumentType.h"
#include "RBDOMApplicationCache.h"
#include "RBDOMCoreException.h"
#include "RBDOMError.h"
#include "RBDOMFileSystem.h"
#include "RBDOMFileSystemSync.h"
#include "RBDOMFormData.h"
#include "RBDOMImplementation.h"
#include "RBDOMMimeType.h"
#include "RBDOMMimeTypeArray.h"
#include "RBDOMNamedFlowCollection.h"
#include "RBDOMParser.h"
#include "RBDOMPath.h"
#include "RBDOMPlugin.h"
#include "RBDOMPluginArray.h"
#include "RBDOMSecurityPolicy.h"
#include "RBDOMSelection.h"
#include "RBDOMSettableTokenList.h"
#include "RBDOMStringList.h"
#include "RBDOMStringMap.h"
#include "RBDOMTokenList.h"
#include "RBDOMURL.h"
#include "RBDOMWindow.h"
#include "RBDOMWindowCSS.h"
#include "RBDynamicsCompressorNode.h"
#include "RBElement.h"
#include "RBEntity.h"
#include "RBEntityReference.h"
#include "RBEntry.h"
#include "RBEntryArray.h"
#include "RBEntryArraySync.h"
#include "RBEntrySync.h"
#include "RBErrorEvent.h"
#include "RBEvent.h"
#include "RBEventException.h"
#include "RBEventSource.h"
#include "RBEventTarget.h"
#include "RBEXTDrawBuffers.h"
#include "RBEXTTextureFilterAnisotropic.h"
#include "RBFile.h"
#include "RBFileEntry.h"
#include "RBFileEntrySync.h"
#include "RBFileError.h"
#include "RBFileException.h"
#include "RBFileList.h"
#include "RBFileReader.h"
#include "RBFileReaderSync.h"
#include "RBFileWriter.h"
#include "RBFileWriterSync.h"
#include "RBFloat32Array.h"
#include "RBFloat64Array.h"
#include "RBFocusEvent.h"
#include "RBFontLoader.h"
#include "RBGainNode.h"
#include "RBGeolocation.h"
#include "RBGeoposition.h"
#include "RBHashChangeEvent.h"
#include "RBHistory.h"
#include "RBHTMLAllCollection.h"
#include "RBHTMLAnchorElement.h"
#include "RBHTMLAppletElement.h"
#include "RBHTMLAreaElement.h"
#include "RBHTMLAudioElement.h"
#include "RBHTMLBaseElement.h"
#include "RBHTMLBaseFontElement.h"
#include "RBHTMLBodyElement.h"
#include "RBHTMLBRElement.h"
#include "RBHTMLButtonElement.h"
#include "RBHTMLCanvasElement.h"
#include "RBHTMLCollection.h"
#include "RBHTMLContentElement.h"
#include "RBHTMLDataListElement.h"
#include "RBHTMLDetailsElement.h"
#include "RBHTMLDialogElement.h"
#include "RBHTMLDirectoryElement.h"
#include "RBHTMLDivElement.h"
#include "RBHTMLDListElement.h"
#include "RBHTMLDocument.h"
#include "RBHTMLElement.h"
#include "RBHTMLEmbedElement.h"
#include "RBHTMLFieldSetElement.h"
#include "RBHTMLFontElement.h"
#include "RBHTMLFormControlsCollection.h"
#include "RBHTMLFormElement.h"
#include "RBHTMLFrameElement.h"
#include "RBHTMLFrameSetElement.h"
#include "RBHTMLHeadElement.h"
#include "RBHTMLHeadingElement.h"
#include "RBHTMLHRElement.h"
#include "RBHTMLHtmlElement.h"
#include "RBHTMLIFrameElement.h"
#include "RBHTMLImageElement.h"
#include "RBHTMLInputElement.h"
#include "RBHTMLKeygenElement.h"
#include "RBHTMLLabelElement.h"
#include "RBHTMLLegendElement.h"
#include "RBHTMLLIElement.h"
#include "RBHTMLLinkElement.h"
#include "RBHTMLMapElement.h"
#include "RBHTMLMarqueeElement.h"
#include "RBHTMLMediaElement.h"
#include "RBHTMLMenuElement.h"
#include "RBHTMLMetaElement.h"
#include "RBHTMLMeterElement.h"
#include "RBHTMLModElement.h"
#include "RBHTMLObjectElement.h"
#include "RBHTMLOListElement.h"
#include "RBHTMLOptGroupElement.h"
#include "RBHTMLOptionElement.h"
#include "RBHTMLOptionsCollection.h"
#include "RBHTMLOutputElement.h"
#include "RBHTMLParagraphElement.h"
#include "RBHTMLParamElement.h"
#include "RBHTMLPreElement.h"
#include "RBHTMLProgressElement.h"
#include "RBHTMLPropertiesCollection.h"
#include "RBHTMLQuoteElement.h"
#include "RBHTMLScriptElement.h"
#include "RBHTMLSelectElement.h"
#include "RBHTMLShadowElement.h"
#include "RBHTMLSourceElement.h"
#include "RBHTMLSpanElement.h"
#include "RBHTMLStyleElement.h"
#include "RBHTMLTableCaptionElement.h"
#include "RBHTMLTableCellElement.h"
#include "RBHTMLTableColElement.h"
#include "RBHTMLTableElement.h"
#include "RBHTMLTableRowElement.h"
#include "RBHTMLTableSectionElement.h"
#include "RBHTMLTemplateElement.h"
#include "RBHTMLTextAreaElement.h"
#include "RBHTMLTitleElement.h"
#include "RBHTMLTrackElement.h"
#include "RBHTMLUListElement.h"
#include "RBHTMLUnknownElement.h"
#include "RBHTMLVideoElement.h"
#include "RBIDBAny.h"
#include "RBIDBCursor.h"
#include "RBIDBDatabase.h"
#include "RBIDBFactory.h"
#include "RBIDBIndex.h"
#include "RBIDBKeyRange.h"
#include "RBIDBObjectStore.h"
#include "RBIDBRequest.h"
#include "RBIDBTransaction.h"
#include "RBIDBVersionChangeEvent.h"
#include "RBImageData.h"
#include "RBInjectedScriptHost.h"
#include "RBInspectorFrontendHost.h"
#include "RBInt16Array.h"
#include "RBInt32Array.h"
#include "RBInt8Array.h"
#include "RBJavaScriptCallFrame.h"
#include "RBKeyboardEvent.h"
#include "RBLocation.h"
#include "RBMallocStatistics.h"
#include "RBMediaController.h"
#include "RBMediaElementAudioSourceNode.h"
#include "RBMediaError.h"
#include "RBMediaKeyError.h"
#include "RBMediaKeyEvent.h"
#include "RBMediaKeyMessageEvent.h"
#include "RBMediaKeyNeededEvent.h"
#include "RBMediaKeys.h"
#include "RBMediaKeySession.h"
#include "RBMediaList.h"
#include "RBMediaQueryList.h"
#include "RBMediaSource.h"
#include "RBMediaStreamAudioSourceNode.h"
#include "RBMemoryInfo.h"
#include "RBMessageChannel.h"
#include "RBMessageEvent.h"
#include "RBMessagePort.h"
#include "RBMetadata.h"
#include "RBMicroDataItemValue.h"
#include "RBMouseEvent.h"
#include "RBMutationEvent.h"
#include "RBMutationObserver.h"
#include "RBMutationRecord.h"
#include "RBNamedNodeMap.h"
#include "RBNavigator.h"
#include "RBNode.h"
#include "RBNodeFilter.h"
#include "RBNodeIterator.h"
#include "RBNodeList.h"
#include "RBNotation.h"
#include "RBNotification.h"
#include "RBNotificationCenter.h"
#include "RBOESElementIndexUint.h"
#include "RBOESStandardDerivatives.h"
#include "RBOESTextureFloat.h"
#include "RBOESTextureHalfFloat.h"
#include "RBOESVertexArrayObject.h"
#include "RBOfflineAudioCompletionEvent.h"
#include "RBOfflineAudioContext.h"
#include "RBOscillatorNode.h"
#include "RBOverflowEvent.h"
#include "RBPageTransitionEvent.h"
#include "RBPannerNode.h"
#include "RBPerformance.h"
#include "RBPerformanceNavigation.h"
#include "RBPerformanceTiming.h"
#include "RBPopStateEvent.h"
#include "RBPositionError.h"
#include "RBProcessingInstruction.h"
#include "RBProgressEvent.h"
#include "RBPropertyNodeList.h"
#include "RBRadioNodeList.h"
#include "RBRange.h"
#include "RBRangeException.h"
#include "RBRect.h"
#include "RBRGBColor.h"
#include "RBScreen.h"
#include "RBScriptProcessorNode.h"
#include "RBScriptProfile.h"
#include "RBScriptProfileNode.h"
#include "RBShadowRoot.h"
#include "RBSharedWorker.h"
#include "RBSharedWorkerContext.h"
#include "RBSourceBuffer.h"
#include "RBSourceBufferList.h"
#include "RBSpeechInputEvent.h"
#include "RBSpeechInputResult.h"
#include "RBSpeechInputResultList.h"
#include "RBSpeechSynthesis.h"
#include "RBSpeechSynthesisEvent.h"
#include "RBSpeechSynthesisUtterance.h"
#include "RBSpeechSynthesisVoice.h"
#include "RBSQLError.h"
#include "RBSQLException.h"
#include "RBSQLResultSet.h"
#include "RBSQLResultSetRowList.h"
#include "RBSQLTransaction.h"
#include "RBSQLTransactionSync.h"
#include "RBStorage.h"
#include "RBStorageEvent.h"
#include "RBStorageInfo.h"
#include "RBStorageQuota.h"
#include "RBStyleMedia.h"
#include "RBStyleSheet.h"
#include "RBStyleSheetList.h"
#include "RBSVGAElement.h"
#include "RBSVGAltGlyphDefElement.h"
#include "RBSVGAltGlyphElement.h"
#include "RBSVGAltGlyphItemElement.h"
#include "RBSVGAngle.h"
#include "RBSVGAnimateColorElement.h"
#include "RBSVGAnimatedAngle.h"
#include "RBSVGAnimatedBoolean.h"
#include "RBSVGAnimatedEnumeration.h"
#include "RBSVGAnimatedInteger.h"
#include "RBSVGAnimatedLength.h"
#include "RBSVGAnimatedLengthList.h"
#include "RBSVGAnimatedNumber.h"
#include "RBSVGAnimatedNumberList.h"
#include "RBSVGAnimatedPreserveAspectRatio.h"
#include "RBSVGAnimatedRect.h"
#include "RBSVGAnimatedString.h"
#include "RBSVGAnimatedTransformList.h"
#include "RBSVGAnimateElement.h"
#include "RBSVGAnimateMotionElement.h"
#include "RBSVGAnimateTransformElement.h"
#include "RBSVGAnimationElement.h"
#include "RBSVGCircleElement.h"
#include "RBSVGClipPathElement.h"
#include "RBSVGColor.h"
#include "RBSVGComponentTransferFunctionElement.h"
#include "RBSVGCursorElement.h"
#include "RBSVGDefsElement.h"
#include "RBSVGDescElement.h"
#include "RBSVGDocument.h"
#include "RBSVGElement.h"
#include "RBSVGElementInstance.h"
#include "RBSVGElementInstanceList.h"
#include "RBSVGEllipseElement.h"
#include "RBSVGException.h"
#include "RBSVGFEBlendElement.h"
#include "RBSVGFEColorMatrixElement.h"
#include "RBSVGFEComponentTransferElement.h"
#include "RBSVGFECompositeElement.h"
#include "RBSVGFEConvolveMatrixElement.h"
#include "RBSVGFEDiffuseLightingElement.h"
#include "RBSVGFEDisplacementMapElement.h"
#include "RBSVGFEDistantLightElement.h"
#include "RBSVGFEDropShadowElement.h"
#include "RBSVGFEFloodElement.h"
#include "RBSVGFEFuncAElement.h"
#include "RBSVGFEFuncBElement.h"
#include "RBSVGFEFuncGElement.h"
#include "RBSVGFEFuncRElement.h"
#include "RBSVGFEGaussianBlurElement.h"
#include "RBSVGFEImageElement.h"
#include "RBSVGFEMergeElement.h"
#include "RBSVGFEMergeNodeElement.h"
#include "RBSVGFEMorphologyElement.h"
#include "RBSVGFEOffsetElement.h"
#include "RBSVGFEPointLightElement.h"
#include "RBSVGFESpecularLightingElement.h"
#include "RBSVGFESpotLightElement.h"
#include "RBSVGFETileElement.h"
#include "RBSVGFETurbulenceElement.h"
#include "RBSVGFilterElement.h"
#include "RBSVGFilterPrimitiveStandardAttributes.h"
#include "RBSVGFontElement.h"
#include "RBSVGFontFaceElement.h"
#include "RBSVGFontFaceFormatElement.h"
#include "RBSVGFontFaceNameElement.h"
#include "RBSVGFontFaceSrcElement.h"
#include "RBSVGFontFaceUriElement.h"
#include "RBSVGForeignObjectElement.h"
#include "RBSVGGElement.h"
#include "RBSVGGlyphElement.h"
#include "RBSVGGlyphRefElement.h"
#include "RBSVGGradientElement.h"
#include "RBSVGHKernElement.h"
#include "RBSVGImageElement.h"
#include "RBSVGLength.h"
#include "RBSVGLengthList.h"
#include "RBSVGLinearGradientElement.h"
#include "RBSVGLineElement.h"
#include "RBSVGMarkerElement.h"
#include "RBSVGMaskElement.h"
#include "RBSVGMatrix.h"
#include "RBSVGMetadataElement.h"
#include "RBSVGMissingGlyphElement.h"
#include "RBSVGMPathElement.h"
#include "RBSVGNumber.h"
#include "RBSVGNumberList.h"
#include "RBSVGPaint.h"
#include "RBSVGPathElement.h"
#include "RBSVGPathSeg.h"
#include "RBSVGPathSegArcAbs.h"
#include "RBSVGPathSegArcRel.h"
#include "RBSVGPathSegClosePath.h"
#include "RBSVGPathSegCurvetoCubicAbs.h"
#include "RBSVGPathSegCurvetoCubicRel.h"
#include "RBSVGPathSegCurvetoCubicSmoothAbs.h"
#include "RBSVGPathSegCurvetoCubicSmoothRel.h"
#include "RBSVGPathSegCurvetoQuadraticAbs.h"
#include "RBSVGPathSegCurvetoQuadraticRel.h"
#include "RBSVGPathSegCurvetoQuadraticSmoothAbs.h"
#include "RBSVGPathSegCurvetoQuadraticSmoothRel.h"
#include "RBSVGPathSegLinetoAbs.h"
#include "RBSVGPathSegLinetoHorizontalAbs.h"
#include "RBSVGPathSegLinetoHorizontalRel.h"
#include "RBSVGPathSegLinetoRel.h"
#include "RBSVGPathSegLinetoVerticalAbs.h"
#include "RBSVGPathSegLinetoVerticalRel.h"
#include "RBSVGPathSegList.h"
#include "RBSVGPathSegMovetoAbs.h"
#include "RBSVGPathSegMovetoRel.h"
#include "RBSVGPatternElement.h"
#include "RBSVGPoint.h"
#include "RBSVGPointList.h"
#include "RBSVGPolygonElement.h"
#include "RBSVGPolylineElement.h"
#include "RBSVGPreserveAspectRatio.h"
#include "RBSVGRadialGradientElement.h"
#include "RBSVGRect.h"
#include "RBSVGRectElement.h"
#include "RBSVGRenderingIntent.h"
#include "RBSVGScriptElement.h"
#include "RBSVGSetElement.h"
#include "RBSVGStopElement.h"
#include "RBSVGStringList.h"
#include "RBSVGStyledElement.h"
#include "RBSVGStyleElement.h"
#include "RBSVGSVGElement.h"
#include "RBSVGSwitchElement.h"
#include "RBSVGSymbolElement.h"
#include "RBSVGTextContentElement.h"
#include "RBSVGTextElement.h"
#include "RBSVGTextPathElement.h"
#include "RBSVGTextPositioningElement.h"
#include "RBSVGTitleElement.h"
#include "RBSVGTransform.h"
#include "RBSVGTransformList.h"
#include "RBSVGTRefElement.h"
#include "RBSVGTSpanElement.h"
#include "RBSVGUnitTypes.h"
#include "RBSVGUseElement.h"
#include "RBSVGViewElement.h"
#include "RBSVGViewSpec.h"
#include "RBSVGVKernElement.h"
#include "RBSVGZoomAndPan.h"
#include "RBSVGZoomEvent.h"
#include "RBText.h"
#include "RBTextEvent.h"
#include "RBTextMetrics.h"
#include "RBTextTrack.h"
#include "RBTextTrackCue.h"
#include "RBTextTrackCueList.h"
#include "RBTextTrackList.h"
#include "RBTimeRanges.h"
#include "RBTouch.h"
#include "RBTouchEvent.h"
#include "RBTouchList.h"
#include "RBTrackEvent.h"
#include "RBTransitionEvent.h"
#include "RBTreeWalker.h"
#include "RBTypeConversions.h"
#include "RBUIEvent.h"
#include "RBUint16Array.h"
#include "RBUint32Array.h"
#include "RBUint8Array.h"
#include "RBUint8ClampedArray.h"
#include "RBValidityState.h"
#include "RBWaveShaperNode.h"
#include "RBWaveTable.h"
#include "RBWebGLActiveInfo.h"
#include "RBWebGLBuffer.h"
#include "RBWebGLCompressedTextureATC.h"
#include "RBWebGLCompressedTexturePVRTC.h"
#include "RBWebGLCompressedTextureS3TC.h"
#include "RBWebGLContextAttributes.h"
#include "RBWebGLContextEvent.h"
#include "RBWebGLDepthTexture.h"
#include "RBWebGLFramebuffer.h"
#include "RBWebGLLoseContext.h"
#include "RBWebGLProgram.h"
#include "RBWebGLRenderbuffer.h"
#include "RBWebGLRenderingContext.h"
#include "RBWebGLShader.h"
#include "RBWebGLShaderPrecisionFormat.h"
#include "RBWebGLTexture.h"
#include "RBWebGLUniformLocation.h"
#include "RBWebGLVertexArrayObjectOES.h"
#include "RBWebKitAnimationEvent.h"
#include "RBWebKitCSSFilterRule.h"
#include "RBWebKitCSSFilterValue.h"
#include "RBWebKitCSSKeyframeRule.h"
#include "RBWebKitCSSKeyframesRule.h"
#include "RBWebKitCSSMatrix.h"
#include "RBWebKitCSSMixFunctionValue.h"
#include "RBWebKitCSSRegionRule.h"
#include "RBWebKitCSSTransformValue.h"
#include "RBWebKitCSSViewportRule.h"
#include "RBWebKitNamedFlow.h"
#include "RBWebKitPoint.h"
#include "RBWebKitTransitionEvent.h"
#include "RBWebSocket.h"
#include "RBWheelEvent.h"
#include "RBWorker.h"
#include "RBWorkerContext.h"
#include "RBWorkerLocation.h"
#include "RBWorkerNavigator.h"
#include "RBXMLHttpRequest.h"
#include "RBXMLHttpRequestException.h"
#include "RBXMLHttpRequestProgressEvent.h"
#include "RBXMLHttpRequestUpload.h"
#include "RBXMLSerializer.h"
#include "RBXPathEvaluator.h"
#include "RBXPathException.h"
#include "RBXPathExpression.h"
#include "RBXPathNSResolver.h"
#include "RBXPathResult.h"
#include "RBXSLTProcessor.h"

namespace WebCore {
    
    void RBInitialization::initializeRubyClasses()
    {
#if ENABLE(WORKERS)
        RBAbstractWorker::Init_AbstractWorker();
#endif
#if ENABLE(WEB_AUDIO)
        RBAnalyserNode::Init_AnalyserNode();
#endif
        RBArrayBuffer::Init_ArrayBuffer();
        RBArrayBufferView::Init_ArrayBufferView();
        RBAttr::Init_Attr();
#if ENABLE(WEB_AUDIO)
        RBAudioBuffer::Init_AudioBuffer();
#endif
#if ENABLE(WEB_AUDIO)
        RBAudioBufferSourceNode::Init_AudioBufferSourceNode();
#endif

#if ENABLE(WEB_AUDIO)
        RBAudioContext::Init_AudioContext();
#endif
#if ENABLE(WEB_AUDIO)
        RBAudioDestinationNode::Init_AudioDestinationNode();
#endif
#if ENABLE(WEB_AUDIO)
        RBAudioListener::Init_AudioListener();
#endif
#if ENABLE(WEB_AUDIO)
        RBAudioNode::Init_AudioNode();
#endif
#if ENABLE(WEB_AUDIO)
        RBAudioParam::Init_AudioParam();
#endif
#if ENABLE(WEB_AUDIO)
        RBAudioProcessingEvent::Init_AudioProcessingEvent();
#endif
#if ENABLE(WEB_AUDIO)
        RBAudioSourceNode::Init_AudioSourceNode();
#endif
        RBBarInfo::Init_BarInfo();
        RBBeforeLoadEvent::Init_BeforeLoadEvent();
#if ENABLE(WEB_AUDIO)
        RBBiquadFilterNode::Init_BiquadFilterNode();
#endif
        RBBlob::Init_Blob();
        RBCanvasGradient::Init_CanvasGradient();
        RBCanvasPattern::Init_CanvasPattern();
#if ENABLE(CANVAS_PROXY)
        RBCanvasProxy::Init_CanvasProxy();
#endif
        RBCanvasRenderingContext::Init_CanvasRenderingContext();
        RBCanvasRenderingContext2D::Init_CanvasRenderingContext2D();
        RBCDATASection::Init_CDATASection();
#if ENABLE(WEB_AUDIO)
        RBChannelMergerNode::Init_ChannelMergerNode();
#endif
#if ENABLE(WEB_AUDIO)
        RBChannelSplitterNode::Init_ChannelSplitterNode();
#endif
        RBCharacterData::Init_CharacterData();
        RBClientRect::Init_ClientRect();
        RBClientRectList::Init_ClientRectList();
        RBClipboard::Init_Clipboard();
        RBCloseEvent::Init_CloseEvent();
        RBComment::Init_Comment();
        RBCompositionEvent::Init_CompositionEvent();
        RBConsole::Init_Console();
#if ENABLE(WEB_AUDIO)
        RBConvolverNode::Init_ConvolverNode();
#endif
#if ENABLE(GEOLOCATION)
        RBCoordinates::Init_Coordinates();
#endif
        RBCounter::Init_Counter();
        RBCrypto::Init_Crypto();
        RBCSSCharsetRule::Init_CSSCharsetRule();
#if ENABLE(FONT_LOAD_EVENTS)
        RBCSSFontFaceLoadEvent::Init_CSSFontFaceLoadEvent();
#endif
        RBCSSFontFaceRule::Init_CSSFontFaceRule();
#if ENABLE(SHADOW_DOM)
        RBCSSHostRule::Init_CSSHostRule();
#endif
        RBCSSImportRule::Init_CSSImportRule();
        RBCSSMediaRule::Init_CSSMediaRule();
        RBCSSPageRule::Init_CSSPageRule();
        RBCSSPrimitiveValue::Init_CSSPrimitiveValue();
        RBCSSRule::Init_CSSRule();
        RBCSSRuleList::Init_CSSRuleList();
        RBCSSStyleDeclaration::Init_CSSStyleDeclaration();
        RBCSSStyleRule::Init_CSSStyleRule();
        RBCSSStyleSheet::Init_CSSStyleSheet();
#if ENABLE(CSS3_CONDITIONAL_RULES)
        RBCSSSupportsRule::Init_CSSSupportsRule();
#endif
        RBCSSUnknownRule::Init_CSSUnknownRule();
        RBCSSValue::Init_CSSValue();
        RBCSSValueList::Init_CSSValueList();
#if ENABLE(CUSTOM_ELEMENTS)
        RBCustomElementConstructor::Init_CustomElementConstructor();
#endif
        RBCustomEvent::Init_CustomEvent();
#if ENABLE(SQL_DATABASE)
        RBDatabase::Init_Database();
#endif
#if ENABLE(SQL_DATABASE)
        RBDatabaseSync::Init_DatabaseSync();
#endif
#if ENABLE(DATA_TRANSFER_ITEMS)
        RBDataTransferItem::Init_DataTransferItem();
#endif
#if ENABLE(DATA_TRANSFER_ITEMS)
        RBDataTransferItemList::Init_DataTransferItemList();
#endif
        RBDataView::Init_DataView();
#if ENABLE(WORKERS)
        RBDedicatedWorkerContext::Init_DedicatedWorkerContext();
#endif
#if ENABLE(WEB_AUDIO)
        RBDelayNode::Init_DelayNode();
#endif
#if ENABLE(DEVICE_ORIENTATION)
        RBDeviceMotionEvent::Init_DeviceMotionEvent();
#endif
#if ENABLE(DEVICE_ORIENTATION)
        RBDeviceOrientationEvent::Init_DeviceOrientationEvent();
#endif
#if ENABLE(FILE_SYSTEM)
        RBDirectoryEntry::Init_DirectoryEntry();
#endif
#if ENABLE(FILE_SYSTEM)
        RBDirectoryEntrySync::Init_DirectoryEntrySync();
#endif
#if ENABLE(FILE_SYSTEM)
        RBDirectoryReader::Init_DirectoryReader();
#endif
#if ENABLE(FILE_SYSTEM)
        RBDirectoryReaderSync::Init_DirectoryReaderSync();
#endif
        RBDocument::Init_Document();
        RBDocumentFragment::Init_DocumentFragment();
        RBDocumentType::Init_DocumentType();
        RBDOMApplicationCache::Init_DOMApplicationCache();
        RBDOMCoreException::Init_DOMCoreException();
        RBDOMError::Init_DOMError();
#if ENABLE(FILE_SYSTEM)
        RBDOMFileSystem::Init_DOMFileSystem();
#endif
#if ENABLE(FILE_SYSTEM)
        RBDOMFileSystemSync::Init_DOMFileSystemSync();
#endif
        RBDOMFormData::Init_DOMFormData();
        RBDOMImplementation::Init_DOMImplementation();
        RBDOMMimeType::Init_DOMMimeType();
        RBDOMMimeTypeArray::Init_DOMMimeTypeArray();
#if ENABLE(CSS_REGIONS)
        RBDOMNamedFlowCollection::Init_DOMNamedFlowCollection();
#endif
        RBDOMParser::Init_DOMParser();
#if ENABLE(CANVAS_PATH)
        RBDOMPath::Init_DOMPath();
#endif
        RBDOMPlugin::Init_DOMPlugin();
        RBDOMPluginArray::Init_DOMPluginArray();
#if ENABLE(CSP_NEXT)
        RBDOMSecurityPolicy::Init_DOMSecurityPolicy();
#endif
        RBDOMSelection::Init_DOMSelection();
        RBDOMSettableTokenList::Init_DOMSettableTokenList();
        RBDOMStringList::Init_DOMStringList();
        RBDOMStringMap::Init_DOMStringMap();
        RBDOMTokenList::Init_DOMTokenList();
#if ENABLE(BLOB)
        RBDOMURL::Init_DOMURL();
#endif
        RBDOMWindow::Init_DOMWindow();
#if ENABLE(CSS3_CONDITIONAL_RULES)
        RBDOMWindowCSS::Init_DOMWindowCSS();
#endif
#if ENABLE(WEB_AUDIO)
        RBDynamicsCompressorNode::Init_DynamicsCompressorNode();
#endif
        RBElement::Init_Element();
        RBEntity::Init_Entity();
        RBEntityReference::Init_EntityReference();
#if ENABLE(FILE_SYSTEM)
        RBEntry::Init_Entry();
#endif
#if ENABLE(FILE_SYSTEM)
        RBEntryArray::Init_EntryArray();
#endif
#if ENABLE(FILE_SYSTEM)
        RBEntryArraySync::Init_EntryArraySync();
#endif
#if ENABLE(FILE_SYSTEM)
        RBEntrySync::Init_EntrySync();
#endif
        RBErrorEvent::Init_ErrorEvent();
        RBEvent::Init_Event();
        RBEventException::Init_EventException();
        RBEventSource::Init_EventSource();
        RBEventTarget::Init_EventTarget();
#if ENABLE(WEBGL)
        RBEXTDrawBuffers::Init_EXTDrawBuffers();
#endif
#if ENABLE(WEBGL)
        RBEXTTextureFilterAnisotropic::Init_EXTTextureFilterAnisotropic();
#endif
        RBFile::Init_File();
#if ENABLE(FILE_SYSTEM)
        RBFileEntry::Init_FileEntry();
#endif
#if ENABLE(FILE_SYSTEM)
        RBFileEntrySync::Init_FileEntrySync();
#endif
#if ENABLE(BLOB) || ENABLE(FILE_SYSTEM)
        RBFileError::Init_FileError();
#endif
#if ENABLE(BLOB) || ENABLE(FILE_SYSTEM)
        RBFileException::Init_FileException();
#endif
        RBFileList::Init_FileList();
#if ENABLE(BLOB)
        RBFileReader::Init_FileReader();
#endif
#if ENABLE(BLOB)
        RBFileReaderSync::Init_FileReaderSync();
#endif
#if ENABLE(FILE_SYSTEM)
        RBFileWriter::Init_FileWriter();
#endif
#if ENABLE(FILE_SYSTEM)
        RBFileWriterSync::Init_FileWriterSync();
#endif
        RBFloat32Array::Init_Float32Array();
        RBFloat64Array::Init_Float64Array();
        RBFocusEvent::Init_FocusEvent();
#if ENABLE(FONT_LOAD_EVENTS)
        RBFontLoader::Init_FontLoader();
#endif
#if ENABLE(WEB_AUDIO)
        RBGainNode::Init_GainNode();
#endif
#if ENABLE(GEOLOCATION)
        RBGeolocation::Init_Geolocation();
#endif
#if ENABLE(GEOLOCATION)
        RBGeoposition::Init_Geoposition();
#endif
        RBHashChangeEvent::Init_HashChangeEvent();
        RBHistory::Init_History();
        RBHTMLAllCollection::Init_HTMLAllCollection();
        RBHTMLAnchorElement::Init_HTMLAnchorElement();
        RBHTMLAppletElement::Init_HTMLAppletElement();
        RBHTMLAreaElement::Init_HTMLAreaElement();
#if ENABLE(VIDEO)
        RBHTMLAudioElement::Init_HTMLAudioElement();
#endif
        RBHTMLBaseElement::Init_HTMLBaseElement();
        RBHTMLBaseFontElement::Init_HTMLBaseFontElement();
        RBHTMLBodyElement::Init_HTMLBodyElement();
        RBHTMLBRElement::Init_HTMLBRElement();
        RBHTMLButtonElement::Init_HTMLButtonElement();
        RBHTMLCanvasElement::Init_HTMLCanvasElement();
        RBHTMLCollection::Init_HTMLCollection();
#if ENABLE(SHADOW_DOM)
        RBHTMLContentElement::Init_HTMLContentElement();
#endif
#if ENABLE(DATALIST_ELEMENT)
        RBHTMLDataListElement::Init_HTMLDataListElement();
#endif
#if ENABLE(DETAILS_ELEMENT)
        RBHTMLDetailsElement::Init_HTMLDetailsElement();
#endif
#if ENABLE(DIALOG_ELEMENT)
        RBHTMLDialogElement::Init_HTMLDialogElement();
#endif
        RBHTMLDirectoryElement::Init_HTMLDirectoryElement();
        RBHTMLDivElement::Init_HTMLDivElement();
        RBHTMLDListElement::Init_HTMLDListElement();
        RBHTMLDocument::Init_HTMLDocument();
        RBHTMLElement::Init_HTMLElement();
        RBHTMLEmbedElement::Init_HTMLEmbedElement();
        RBHTMLFieldSetElement::Init_HTMLFieldSetElement();
        RBHTMLFontElement::Init_HTMLFontElement();
        RBHTMLFormControlsCollection::Init_HTMLFormControlsCollection();
        RBHTMLFormElement::Init_HTMLFormElement();
        RBHTMLFrameElement::Init_HTMLFrameElement();
        RBHTMLFrameSetElement::Init_HTMLFrameSetElement();
        RBHTMLHeadElement::Init_HTMLHeadElement();
        RBHTMLHeadingElement::Init_HTMLHeadingElement();
        RBHTMLHRElement::Init_HTMLHRElement();
        RBHTMLHtmlElement::Init_HTMLHtmlElement();
        RBHTMLIFrameElement::Init_HTMLIFrameElement();
        RBHTMLImageElement::Init_HTMLImageElement();
        RBHTMLInputElement::Init_HTMLInputElement();
        RBHTMLKeygenElement::Init_HTMLKeygenElement();
        RBHTMLLabelElement::Init_HTMLLabelElement();
        RBHTMLLegendElement::Init_HTMLLegendElement();
        RBHTMLLIElement::Init_HTMLLIElement();
        RBHTMLLinkElement::Init_HTMLLinkElement();
        RBHTMLMapElement::Init_HTMLMapElement();
        RBHTMLMarqueeElement::Init_HTMLMarqueeElement();
#if ENABLE(VIDEO)
        RBHTMLMediaElement::Init_HTMLMediaElement();
#endif
        RBHTMLMenuElement::Init_HTMLMenuElement();
        RBHTMLMetaElement::Init_HTMLMetaElement();
#if ENABLE(METER_ELEMENT)
        RBHTMLMeterElement::Init_HTMLMeterElement();
#endif
        RBHTMLModElement::Init_HTMLModElement();
        RBHTMLObjectElement::Init_HTMLObjectElement();
        RBHTMLOListElement::Init_HTMLOListElement();
        RBHTMLOptGroupElement::Init_HTMLOptGroupElement();
        RBHTMLOptionElement::Init_HTMLOptionElement();
        RBHTMLOptionsCollection::Init_HTMLOptionsCollection();
        RBHTMLOutputElement::Init_HTMLOutputElement();
        RBHTMLParagraphElement::Init_HTMLParagraphElement();
        RBHTMLParamElement::Init_HTMLParamElement();
        RBHTMLPreElement::Init_HTMLPreElement();
#if ENABLE(PROGRESS_ELEMENT)
        RBHTMLProgressElement::Init_HTMLProgressElement();
#endif
#if ENABLE(MICRODATA)
        RBHTMLPropertiesCollection::Init_HTMLPropertiesCollection();
#endif
        RBHTMLQuoteElement::Init_HTMLQuoteElement();
        RBHTMLScriptElement::Init_HTMLScriptElement();
        RBHTMLSelectElement::Init_HTMLSelectElement();
#if ENABLE(SHADOW_DOM)
        RBHTMLShadowElement::Init_HTMLShadowElement();
#endif
#if ENABLE(VIDEO)
        RBHTMLSourceElement::Init_HTMLSourceElement();
#endif
        RBHTMLSpanElement::Init_HTMLSpanElement();
        RBHTMLStyleElement::Init_HTMLStyleElement();
        RBHTMLTableCaptionElement::Init_HTMLTableCaptionElement();
        RBHTMLTableCellElement::Init_HTMLTableCellElement();
        RBHTMLTableColElement::Init_HTMLTableColElement();
        RBHTMLTableElement::Init_HTMLTableElement();
        RBHTMLTableRowElement::Init_HTMLTableRowElement();
        RBHTMLTableSectionElement::Init_HTMLTableSectionElement();
#if ENABLE(TEMPLATE_ELEMENT)
        RBHTMLTemplateElement::Init_HTMLTemplateElement();
#endif
        RBHTMLTextAreaElement::Init_HTMLTextAreaElement();
        RBHTMLTitleElement::Init_HTMLTitleElement();
#if ENABLE(VIDEO_TRACK)
        RBHTMLTrackElement::Init_HTMLTrackElement();
#endif
        RBHTMLUListElement::Init_HTMLUListElement();
        RBHTMLUnknownElement::Init_HTMLUnknownElement();
#if ENABLE(VIDEO)
        RBHTMLVideoElement::Init_HTMLVideoElement();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBAny::Init_IDBAny();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBCursor::Init_IDBCursor();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBDatabase::Init_IDBDatabase();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBFactory::Init_IDBFactory();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBIndex::Init_IDBIndex();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBKeyRange::Init_IDBKeyRange();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBObjectStore::Init_IDBObjectStore();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBRequest::Init_IDBRequest();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBTransaction::Init_IDBTransaction();
#endif
#if ENABLE(INDEXED_DATABASE)
        RBIDBVersionChangeEvent::Init_IDBVersionChangeEvent();
#endif
        RBImageData::Init_ImageData();
#if ENABLE(INSPECTOR)
        RBInjectedScriptHost::Init_InjectedScriptHost();
#endif
#if ENABLE(INSPECTOR)
        RBInspectorFrontendHost::Init_InspectorFrontendHost();
#endif
        RBInt16Array::Init_Int16Array();
        RBInt32Array::Init_Int32Array();
        RBInt8Array::Init_Int8Array();
#if ENABLE(JAVASCRIPT_DEBUGGER)
        RBJavaScriptCallFrame::Init_JavaScriptCallFrame();
#endif
        RBKeyboardEvent::Init_KeyboardEvent();
        RBLocation::Init_Location();
        RBMallocStatistics::Init_MallocStatistics();
#if ENABLE(VIDEO)
        RBMediaController::Init_MediaController();
#endif
#if ENABLE(VIDEO) && ENABLE(WEB_AUDIO)
        RBMediaElementAudioSourceNode::Init_MediaElementAudioSourceNode();
#endif
#if ENABLE(VIDEO)
        RBMediaError::Init_MediaError();
#endif
#if ENABLE(ENCRYPTED_MEDIA) || ENABLE(ENCRYPTED_MEDIA_V2)
        RBMediaKeyError::Init_MediaKeyError();
#endif
#if ENABLE(ENCRYPTED_MEDIA)
        RBMediaKeyEvent::Init_MediaKeyEvent();
#endif
#if ENABLE(ENCRYPTED_MEDIA_V2)
        RBMediaKeyMessageEvent::Init_MediaKeyMessageEvent();
#endif
#if ENABLE(ENCRYPTED_MEDIA_V2)
        RBMediaKeyNeededEvent::Init_MediaKeyNeededEvent();
#endif
#if ENABLE(ENCRYPTED_MEDIA_V2)
        RBMediaKeys::Init_MediaKeys();
#endif
#if ENABLE(ENCRYPTED_MEDIA_V2)
        RBMediaKeySession::Init_MediaKeySession();
#endif
        RBMediaList::Init_MediaList();
        RBMediaQueryList::Init_MediaQueryList();
#if ENABLE(MEDIA_SOURCE)
        RBMediaSource::Init_MediaSource();
#endif
#if ENABLE(MEDIA_STREAM) && ENABLE(WEB_AUDIO)
        RBMediaStreamAudioSourceNode::Init_MediaStreamAudioSourceNode();
#endif
        RBMemoryInfo::Init_MemoryInfo();
        RBMessageChannel::Init_MessageChannel();
        RBMessageEvent::Init_MessageEvent();
        RBMessagePort::Init_MessagePort();
#if ENABLE(FILE_SYSTEM)
        RBMetadata::Init_Metadata();
#endif
#if ENABLE(MICRODATA)
        RBMicroDataItemValue::Init_MicroDataItemValue();
#endif
        RBMouseEvent::Init_MouseEvent();
        RBMutationEvent::Init_MutationEvent();
        RBMutationObserver::Init_MutationObserver();
        RBMutationRecord::Init_MutationRecord();
        RBNamedNodeMap::Init_NamedNodeMap();
        RBNavigator::Init_Navigator();
        RBNode::Init_Node();
        RBNodeFilter::Init_NodeFilter();
        RBNodeIterator::Init_NodeIterator();
        RBNodeList::Init_NodeList();
        RBNotation::Init_Notation();
#if ENABLE(LEGACY_NOTIFICATIONS) || ENABLE(NOTIFICATIONS)
        RBNotification::Init_Notification();
#endif
#if ENABLE(LEGACY_NOTIFICATIONS)
        RBNotificationCenter::Init_NotificationCenter();
#endif
#if ENABLE(WEBGL)
        RBOESElementIndexUint::Init_OESElementIndexUint();
#endif
#if ENABLE(WEBGL)
        RBOESStandardDerivatives::Init_OESStandardDerivatives();
#endif
#if ENABLE(WEBGL)
        RBOESTextureFloat::Init_OESTextureFloat();
#endif
#if ENABLE(WEBGL)
        RBOESTextureHalfFloat::Init_OESTextureHalfFloat();
#endif
#if ENABLE(WEBGL)
        RBOESVertexArrayObject::Init_OESVertexArrayObject();
#endif
#if ENABLE(WEB_AUDIO)
        RBOfflineAudioCompletionEvent::Init_OfflineAudioCompletionEvent();
#endif
#if ENABLE(WEB_AUDIO)
        RBOfflineAudioContext::Init_OfflineAudioContext();
#endif
#if ENABLE(WEB_AUDIO)
        RBOscillatorNode::Init_OscillatorNode();
#endif
        RBOverflowEvent::Init_OverflowEvent();
        RBPageTransitionEvent::Init_PageTransitionEvent();
#if ENABLE(WEB_AUDIO)
        RBPannerNode::Init_PannerNode();
#endif
#if ENABLE(WEB_TIMING)
        RBPerformance::Init_Performance();
#endif
#if ENABLE(WEB_TIMING)
        RBPerformanceNavigation::Init_PerformanceNavigation();
#endif
#if ENABLE(WEB_TIMING)
        RBPerformanceTiming::Init_PerformanceTiming();
#endif
        RBPopStateEvent::Init_PopStateEvent();
#if ENABLE(GEOLOCATION)
        RBPositionError::Init_PositionError();
#endif
        RBProcessingInstruction::Init_ProcessingInstruction();
        RBProgressEvent::Init_ProgressEvent();
#if ENABLE(MICRODATA)
        RBPropertyNodeList::Init_PropertyNodeList();
#endif
        RBRadioNodeList::Init_RadioNodeList();
        RBRange::Init_Range();
        RBRangeException::Init_RangeException();
        RBRect::Init_Rect();
        RBRGBColor::Init_RGBColor();
        RBScreen::Init_Screen();
#if ENABLE(WEB_AUDIO)
        RBScriptProcessorNode::Init_ScriptProcessorNode();
#endif
#if ENABLE(JAVASCRIPT_DEBUGGER)
        RBScriptProfile::Init_ScriptProfile();
#endif
#if ENABLE(JAVASCRIPT_DEBUGGER)
        RBScriptProfileNode::Init_ScriptProfileNode();
#endif
#if ENABLE(SHADOW_DOM)
        RBShadowRoot::Init_ShadowRoot();
#endif
#if ENABLE(SHARED_WORKERS)
        RBSharedWorker::Init_SharedWorker();
#endif
#if ENABLE(SHARED_WORKERS)
        RBSharedWorkerContext::Init_SharedWorkerContext();
#endif
#if ENABLE(MEDIA_SOURCE)
        RBSourceBuffer::Init_SourceBuffer();
#endif
#if ENABLE(MEDIA_SOURCE)
        RBSourceBufferList::Init_SourceBufferList();
#endif
#if ENABLE(INPUT_SPEECH)
        RBSpeechInputEvent::Init_SpeechInputEvent();
#endif
#if ENABLE(INPUT_SPEECH)
        RBSpeechInputResult::Init_SpeechInputResult();
#endif
#if ENABLE(INPUT_SPEECH)
        RBSpeechInputResultList::Init_SpeechInputResultList();
#endif
#if ENABLE(SPEECH_SYNTHESIS)
        RBSpeechSynthesis::Init_SpeechSynthesis();
#endif
#if ENABLE(SPEECH_SYNTHESIS)
        RBSpeechSynthesisEvent::Init_SpeechSynthesisEvent();
#endif
#if ENABLE(SPEECH_SYNTHESIS)
        RBSpeechSynthesisUtterance::Init_SpeechSynthesisUtterance();
#endif
#if ENABLE(SPEECH_SYNTHESIS)
        RBSpeechSynthesisVoice::Init_SpeechSynthesisVoice();
#endif
#if ENABLE(SQL_DATABASE)
        RBSQLError::Init_SQLError();
#endif
#if ENABLE(SQL_DATABASE)
        RBSQLException::Init_SQLException();
#endif
#if ENABLE(SQL_DATABASE)
        RBSQLResultSet::Init_SQLResultSet();
#endif
#if ENABLE(SQL_DATABASE)
        RBSQLResultSetRowList::Init_SQLResultSetRowList();
#endif
#if ENABLE(SQL_DATABASE)
        RBSQLTransaction::Init_SQLTransaction();
#endif
#if ENABLE(SQL_DATABASE)
        RBSQLTransactionSync::Init_SQLTransactionSync();
#endif
        RBStorage::Init_Storage();
        RBStorageEvent::Init_StorageEvent();
#if ENABLE(QUOTA)
        RBStorageInfo::Init_StorageInfo();
#endif
#if ENABLE(QUOTA)
        RBStorageQuota::Init_StorageQuota();
#endif
        RBStyleMedia::Init_StyleMedia();
        RBStyleSheet::Init_StyleSheet();
        RBStyleSheetList::Init_StyleSheetList();
#if ENABLE(SVG)
        RBSVGAElement::Init_SVGAElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGAltGlyphDefElement::Init_SVGAltGlyphDefElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGAltGlyphElement::Init_SVGAltGlyphElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGAltGlyphItemElement::Init_SVGAltGlyphItemElement();
#endif
#if ENABLE(SVG)
        RBSVGAngle::Init_SVGAngle();
#endif
#if ENABLE(SVG)
        RBSVGAnimateColorElement::Init_SVGAnimateColorElement();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedAngle::Init_SVGAnimatedAngle();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedBoolean::Init_SVGAnimatedBoolean();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedEnumeration::Init_SVGAnimatedEnumeration();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedInteger::Init_SVGAnimatedInteger();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedLength::Init_SVGAnimatedLength();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedLengthList::Init_SVGAnimatedLengthList();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedNumber::Init_SVGAnimatedNumber();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedNumberList::Init_SVGAnimatedNumberList();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedPreserveAspectRatio::Init_SVGAnimatedPreserveAspectRatio();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedRect::Init_SVGAnimatedRect();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedString::Init_SVGAnimatedString();
#endif
#if ENABLE(SVG)
        RBSVGAnimatedTransformList::Init_SVGAnimatedTransformList();
#endif
#if ENABLE(SVG)
        RBSVGAnimateElement::Init_SVGAnimateElement();
#endif
#if ENABLE(SVG)
        RBSVGAnimateMotionElement::Init_SVGAnimateMotionElement();
#endif
#if ENABLE(SVG)
        RBSVGAnimateTransformElement::Init_SVGAnimateTransformElement();
#endif
#if ENABLE(SVG)
        RBSVGAnimationElement::Init_SVGAnimationElement();
#endif
#if ENABLE(SVG)
        RBSVGCircleElement::Init_SVGCircleElement();
#endif
#if ENABLE(SVG)
        RBSVGClipPathElement::Init_SVGClipPathElement();
#endif
#if ENABLE(SVG)
        RBSVGColor::Init_SVGColor();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGComponentTransferFunctionElement::Init_SVGComponentTransferFunctionElement();
#endif
#if ENABLE(SVG)
        RBSVGCursorElement::Init_SVGCursorElement();
#endif
#if ENABLE(SVG)
        RBSVGDefsElement::Init_SVGDefsElement();
#endif
#if ENABLE(SVG)
        RBSVGDescElement::Init_SVGDescElement();
#endif
#if ENABLE(SVG)
        RBSVGDocument::Init_SVGDocument();
#endif
#if ENABLE(SVG)
        RBSVGElement::Init_SVGElement();
#endif
#if ENABLE(SVG)
        RBSVGElementInstance::Init_SVGElementInstance();
#endif
#if ENABLE(SVG)
        RBSVGElementInstanceList::Init_SVGElementInstanceList();
#endif
#if ENABLE(SVG)
        RBSVGEllipseElement::Init_SVGEllipseElement();
#endif
#if ENABLE(SVG)
        RBSVGException::Init_SVGException();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEBlendElement::Init_SVGFEBlendElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEColorMatrixElement::Init_SVGFEColorMatrixElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEComponentTransferElement::Init_SVGFEComponentTransferElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFECompositeElement::Init_SVGFECompositeElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEConvolveMatrixElement::Init_SVGFEConvolveMatrixElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEDiffuseLightingElement::Init_SVGFEDiffuseLightingElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEDisplacementMapElement::Init_SVGFEDisplacementMapElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEDistantLightElement::Init_SVGFEDistantLightElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEDropShadowElement::Init_SVGFEDropShadowElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEFloodElement::Init_SVGFEFloodElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEFuncAElement::Init_SVGFEFuncAElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEFuncBElement::Init_SVGFEFuncBElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEFuncGElement::Init_SVGFEFuncGElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEFuncRElement::Init_SVGFEFuncRElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEGaussianBlurElement::Init_SVGFEGaussianBlurElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEImageElement::Init_SVGFEImageElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEMergeElement::Init_SVGFEMergeElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEMergeNodeElement::Init_SVGFEMergeNodeElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEMorphologyElement::Init_SVGFEMorphologyElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEOffsetElement::Init_SVGFEOffsetElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFEPointLightElement::Init_SVGFEPointLightElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFESpecularLightingElement::Init_SVGFESpecularLightingElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFESpotLightElement::Init_SVGFESpotLightElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFETileElement::Init_SVGFETileElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFETurbulenceElement::Init_SVGFETurbulenceElement();
#endif
#if ENABLE(FILTERS) && ENABLE(SVG)
        RBSVGFilterElement::Init_SVGFilterElement();
#endif
#if ENABLE(SVG)
        RBSVGFilterPrimitiveStandardAttributes::Init_SVGFilterPrimitiveStandardAttributes();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGFontElement::Init_SVGFontElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGFontFaceElement::Init_SVGFontFaceElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGFontFaceFormatElement::Init_SVGFontFaceFormatElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGFontFaceNameElement::Init_SVGFontFaceNameElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGFontFaceSrcElement::Init_SVGFontFaceSrcElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGFontFaceUriElement::Init_SVGFontFaceUriElement();
#endif
#if ENABLE(SVG)
        RBSVGForeignObjectElement::Init_SVGForeignObjectElement();
#endif
#if ENABLE(SVG)
        RBSVGGElement::Init_SVGGElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGGlyphElement::Init_SVGGlyphElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGGlyphRefElement::Init_SVGGlyphRefElement();
#endif
#if ENABLE(SVG)
        RBSVGGradientElement::Init_SVGGradientElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGHKernElement::Init_SVGHKernElement();
#endif
#if ENABLE(SVG)
        RBSVGImageElement::Init_SVGImageElement();
#endif
#if ENABLE(SVG)
        RBSVGLength::Init_SVGLength();
#endif
#if ENABLE(SVG)
        RBSVGLengthList::Init_SVGLengthList();
#endif
#if ENABLE(SVG)
        RBSVGLinearGradientElement::Init_SVGLinearGradientElement();
#endif
#if ENABLE(SVG)
        RBSVGLineElement::Init_SVGLineElement();
#endif
#if ENABLE(SVG)
        RBSVGMarkerElement::Init_SVGMarkerElement();
#endif
#if ENABLE(SVG)
        RBSVGMaskElement::Init_SVGMaskElement();
#endif
#if ENABLE(SVG)
        RBSVGMatrix::Init_SVGMatrix();
#endif
#if ENABLE(SVG)
        RBSVGMetadataElement::Init_SVGMetadataElement();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGMissingGlyphElement::Init_SVGMissingGlyphElement();
#endif
#if ENABLE(SVG)
        RBSVGMPathElement::Init_SVGMPathElement();
#endif
#if ENABLE(SVG)
        RBSVGNumber::Init_SVGNumber();
#endif
#if ENABLE(SVG)
        RBSVGNumberList::Init_SVGNumberList();
#endif
#if ENABLE(SVG)
        RBSVGPaint::Init_SVGPaint();
#endif
#if ENABLE(SVG)
        RBSVGPathElement::Init_SVGPathElement();
#endif
#if ENABLE(SVG)
        RBSVGPathSeg::Init_SVGPathSeg();
#endif
#if ENABLE(SVG)
        RBSVGPathSegArcAbs::Init_SVGPathSegArcAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegArcRel::Init_SVGPathSegArcRel();
#endif
#if ENABLE(SVG)
        RBSVGPathSegClosePath::Init_SVGPathSegClosePath();
#endif
#if ENABLE(SVG)
        RBSVGPathSegCurvetoCubicAbs::Init_SVGPathSegCurvetoCubicAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegCurvetoCubicRel::Init_SVGPathSegCurvetoCubicRel();
#endif
#if ENABLE(SVG)
        RBSVGPathSegCurvetoCubicSmoothAbs::Init_SVGPathSegCurvetoCubicSmoothAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegCurvetoCubicSmoothRel::Init_SVGPathSegCurvetoCubicSmoothRel();
#endif
#if ENABLE(SVG)
        RBSVGPathSegCurvetoQuadraticAbs::Init_SVGPathSegCurvetoQuadraticAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegCurvetoQuadraticRel::Init_SVGPathSegCurvetoQuadraticRel();
#endif
#if ENABLE(SVG)
        RBSVGPathSegCurvetoQuadraticSmoothAbs::Init_SVGPathSegCurvetoQuadraticSmoothAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegCurvetoQuadraticSmoothRel::Init_SVGPathSegCurvetoQuadraticSmoothRel();
#endif
#if ENABLE(SVG)
        RBSVGPathSegLinetoAbs::Init_SVGPathSegLinetoAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegLinetoHorizontalAbs::Init_SVGPathSegLinetoHorizontalAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegLinetoHorizontalRel::Init_SVGPathSegLinetoHorizontalRel();
#endif
#if ENABLE(SVG)
        RBSVGPathSegLinetoRel::Init_SVGPathSegLinetoRel();
#endif
#if ENABLE(SVG)
        RBSVGPathSegLinetoVerticalAbs::Init_SVGPathSegLinetoVerticalAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegLinetoVerticalRel::Init_SVGPathSegLinetoVerticalRel();
#endif
#if ENABLE(SVG)
        RBSVGPathSegList::Init_SVGPathSegList();
#endif
#if ENABLE(SVG)
        RBSVGPathSegMovetoAbs::Init_SVGPathSegMovetoAbs();
#endif
#if ENABLE(SVG)
        RBSVGPathSegMovetoRel::Init_SVGPathSegMovetoRel();
#endif
#if ENABLE(SVG)
        RBSVGPatternElement::Init_SVGPatternElement();
#endif
#if ENABLE(SVG)
        RBSVGPoint::Init_SVGPoint();
#endif
#if ENABLE(SVG)
        RBSVGPointList::Init_SVGPointList();
#endif
#if ENABLE(SVG)
        RBSVGPolygonElement::Init_SVGPolygonElement();
#endif
#if ENABLE(SVG)
        RBSVGPolylineElement::Init_SVGPolylineElement();
#endif
#if ENABLE(SVG)
        RBSVGPreserveAspectRatio::Init_SVGPreserveAspectRatio();
#endif
#if ENABLE(SVG)
        RBSVGRadialGradientElement::Init_SVGRadialGradientElement();
#endif
#if ENABLE(SVG)
        RBSVGRect::Init_SVGRect();
#endif
#if ENABLE(SVG)
        RBSVGRectElement::Init_SVGRectElement();
#endif
#if ENABLE(SVG)
        RBSVGRenderingIntent::Init_SVGRenderingIntent();
#endif
#if ENABLE(SVG)
        RBSVGScriptElement::Init_SVGScriptElement();
#endif
#if ENABLE(SVG)
        RBSVGSetElement::Init_SVGSetElement();
#endif
#if ENABLE(SVG)
        RBSVGStopElement::Init_SVGStopElement();
#endif
#if ENABLE(SVG)
        RBSVGStringList::Init_SVGStringList();
#endif
#if ENABLE(SVG)
        RBSVGStyledElement::Init_SVGStyledElement();
#endif
#if ENABLE(SVG)
        RBSVGStyleElement::Init_SVGStyleElement();
#endif
#if ENABLE(SVG)
        RBSVGSVGElement::Init_SVGSVGElement();
#endif
#if ENABLE(SVG)
        RBSVGSwitchElement::Init_SVGSwitchElement();
#endif
#if ENABLE(SVG)
        RBSVGSymbolElement::Init_SVGSymbolElement();
#endif
#if ENABLE(SVG)
        RBSVGTextContentElement::Init_SVGTextContentElement();
#endif
#if ENABLE(SVG)
        RBSVGTextElement::Init_SVGTextElement();
#endif
#if ENABLE(SVG)
        RBSVGTextPathElement::Init_SVGTextPathElement();
#endif
#if ENABLE(SVG)
        RBSVGTextPositioningElement::Init_SVGTextPositioningElement();
#endif
#if ENABLE(SVG)
        RBSVGTitleElement::Init_SVGTitleElement();
#endif
#if ENABLE(SVG)
        RBSVGTransform::Init_SVGTransform();
#endif
#if ENABLE(SVG)
        RBSVGTransformList::Init_SVGTransformList();
#endif
#if ENABLE(SVG)
        RBSVGTRefElement::Init_SVGTRefElement();
#endif
#if ENABLE(SVG)
        RBSVGTSpanElement::Init_SVGTSpanElement();
#endif
#if ENABLE(SVG)
        RBSVGUnitTypes::Init_SVGUnitTypes();
#endif
#if ENABLE(SVG)
        RBSVGUseElement::Init_SVGUseElement();
#endif
#if ENABLE(SVG)
        RBSVGViewElement::Init_SVGViewElement();
#endif
#if ENABLE(SVG)
        RBSVGViewSpec::Init_SVGViewSpec();
#endif
#if ENABLE(SVG) && ENABLE(SVG_FONTS)
        RBSVGVKernElement::Init_SVGVKernElement();
#endif
#if ENABLE(SVG)
        RBSVGZoomAndPan::Init_SVGZoomAndPan();
#endif
#if ENABLE(SVG)
        RBSVGZoomEvent::Init_SVGZoomEvent();
#endif
        RBText::Init_Text();
        RBTextEvent::Init_TextEvent();
        RBTextMetrics::Init_TextMetrics();
#if ENABLE(VIDEO_TRACK)
        RBTextTrack::Init_TextTrack();
#endif
#if ENABLE(VIDEO_TRACK)
        RBTextTrackCue::Init_TextTrackCue();
#endif
#if ENABLE(VIDEO_TRACK)
        RBTextTrackCueList::Init_TextTrackCueList();
#endif
#if ENABLE(VIDEO_TRACK)
        RBTextTrackList::Init_TextTrackList();
#endif
#if ENABLE(VIDEO)
        RBTimeRanges::Init_TimeRanges();
#endif
#if ENABLE(TOUCH_EVENTS)
        RBTouch::Init_Touch();
#endif
#if ENABLE(TOUCH_EVENTS)
        RBTouchEvent::Init_TouchEvent();
#endif
#if ENABLE(TOUCH_EVENTS)
        RBTouchList::Init_TouchList();
#endif
#if ENABLE(VIDEO_TRACK)
        RBTrackEvent::Init_TrackEvent();
#endif
        RBTransitionEvent::Init_TransitionEvent();
        RBTreeWalker::Init_TreeWalker();
        RBTypeConversions::Init_TypeConversions();
        RBUIEvent::Init_UIEvent();
        RBUint16Array::Init_Uint16Array();
        RBUint32Array::Init_Uint32Array();
        RBUint8Array::Init_Uint8Array();
        RBUint8ClampedArray::Init_Uint8ClampedArray();
        RBValidityState::Init_ValidityState();
#if ENABLE(WEB_AUDIO)
        RBWaveShaperNode::Init_WaveShaperNode();
#endif
#if ENABLE(WEB_AUDIO)
        RBWaveTable::Init_WaveTable();
#endif
#if ENABLE(WEBGL)
        RBWebGLActiveInfo::Init_WebGLActiveInfo();
#endif
#if ENABLE(WEBGL)
        RBWebGLBuffer::Init_WebGLBuffer();
#endif
#if ENABLE(WEBGL)
        RBWebGLCompressedTextureATC::Init_WebGLCompressedTextureATC();
#endif
#if ENABLE(WEBGL)
        RBWebGLCompressedTexturePVRTC::Init_WebGLCompressedTexturePVRTC();
#endif
#if ENABLE(WEBGL)
        RBWebGLCompressedTextureS3TC::Init_WebGLCompressedTextureS3TC();
#endif
#if ENABLE(WEBGL)
        RBWebGLContextAttributes::Init_WebGLContextAttributes();
#endif
#if ENABLE(WEBGL)
        RBWebGLContextEvent::Init_WebGLContextEvent();
#endif
#if ENABLE(WEBGL)
        RBWebGLDepthTexture::Init_WebGLDepthTexture();
#endif
#if ENABLE(WEBGL)
        RBWebGLFramebuffer::Init_WebGLFramebuffer();
#endif
#if ENABLE(WEBGL)
        RBWebGLLoseContext::Init_WebGLLoseContext();
#endif
#if ENABLE(WEBGL)
        RBWebGLProgram::Init_WebGLProgram();
#endif
#if ENABLE(WEBGL)
        RBWebGLRenderbuffer::Init_WebGLRenderbuffer();
#endif
#if ENABLE(WEBGL)
        RBWebGLRenderingContext::Init_WebGLRenderingContext();
#endif
#if ENABLE(WEBGL)
        RBWebGLShader::Init_WebGLShader();
#endif
#if ENABLE(WEBGL)
        RBWebGLShaderPrecisionFormat::Init_WebGLShaderPrecisionFormat();
#endif
#if ENABLE(WEBGL)
        RBWebGLTexture::Init_WebGLTexture();
#endif
#if ENABLE(WEBGL)
        RBWebGLUniformLocation::Init_WebGLUniformLocation();
#endif
#if ENABLE(WEBGL)
        RBWebGLVertexArrayObjectOES::Init_WebGLVertexArrayObjectOES();
#endif
        RBWebKitAnimationEvent::Init_WebKitAnimationEvent();
#if ENABLE(CSS_SHADERS)
        RBWebKitCSSFilterRule::Init_WebKitCSSFilterRule();
#endif
#if ENABLE(CSS_FILTERS)
        RBWebKitCSSFilterValue::Init_WebKitCSSFilterValue();
#endif
        RBWebKitCSSKeyframeRule::Init_WebKitCSSKeyframeRule();
        RBWebKitCSSKeyframesRule::Init_WebKitCSSKeyframesRule();
        RBWebKitCSSMatrix::Init_WebKitCSSMatrix();
#if ENABLE(CSS_SHADERS)
        RBWebKitCSSMixFunctionValue::Init_WebKitCSSMixFunctionValue();
#endif
#if ENABLE(CSS_REGIONS)
        RBWebKitCSSRegionRule::Init_WebKitCSSRegionRule();
#endif
        RBWebKitCSSTransformValue::Init_WebKitCSSTransformValue();
#if ENABLE(CSS_DEVICE_ADAPTATION)
        RBWebKitCSSViewportRule::Init_WebKitCSSViewportRule();
#endif
        RBWebKitNamedFlow::Init_WebKitNamedFlow();
        RBWebKitPoint::Init_WebKitPoint();
        RBWebKitTransitionEvent::Init_WebKitTransitionEvent();
#if ENABLE(WEB_SOCKETS)
        RBWebSocket::Init_WebSocket();
#endif
        RBWheelEvent::Init_WheelEvent();
#if ENABLE(WORKERS)
        RBWorker::Init_Worker();
#endif
#if ENABLE(WORKERS)
        RBWorkerContext::Init_WorkerContext();
#endif
#if ENABLE(WORKERS)
        RBWorkerLocation::Init_WorkerLocation();
#endif
#if ENABLE(WORKERS)
        RBWorkerNavigator::Init_WorkerNavigator();
#endif
        RBXMLHttpRequest::Init_XMLHttpRequest();
        RBXMLHttpRequestException::Init_XMLHttpRequestException();
        RBXMLHttpRequestProgressEvent::Init_XMLHttpRequestProgressEvent();
        RBXMLHttpRequestUpload::Init_XMLHttpRequestUpload();
        RBXMLSerializer::Init_XMLSerializer();
        RBXPathEvaluator::Init_XPathEvaluator();
        RBXPathException::Init_XPathException();
        RBXPathExpression::Init_XPathExpression();
        RBXPathNSResolver::Init_XPathNSResolver();
        RBXPathResult::Init_XPathResult();
#if ENABLE(XSLT)
        RBXSLTProcessor::Init_XSLTProcessor();
#endif
    }
    
} // namespace WebCore
